#!/usr/bin/env python3

import sys

sequence = 'CCATCTGTTTAGCTCGATCATCCCGATGCTAGGCTATTGGGCCCAATGGCCGTTTTACGGTAGACACCATGCAGCTTTGGCACGGGCAAGGAGGAAACCCAGGTGTTCATAATTGAAACGCATGTTATCTGATGCGGCCTTTAGAGTCGTATCTGTAACGGGGCGAAGCGTACTAGTGTGAGTACCGCCGATTGTGGTAAACAAAGCCCTTCACTGCCGCATGTCTAGAATAGGTACTGGAAAACTAAAAATGGCCAATAGGTCCTGTTCTACAGCTGCCGCTCACGTCTGCCCGAGGCGCTCGTTTCTTCGCCGAGCGGAAACGGGTTGCCCTAGCAAGCCCCACTAGGGGTTGGACAACCGCATTAACCATAGGCTATGGTCACTGTCTCATTCAAGACTGCTTATCATCTGTGGAACTAGGGATTTCCGCTCGGGACGCGCTGCTGACGTTAACCCGGATCCTAAGGACTTCTCCCGTCCGCCAATTGTGTCAGTACTTGTCCTTAGCTAGTGTTGATACGTGTCTTTACTTTAGTGCCCATTCAGTCGTGACAACTGCTAAGACTAGAGCTGATCGGGGACAATTCCGACTCACTGTCGCAGAGCTACTGGCGGACTGTGAGTGGCGTCTTCATGATATCCACCGCACTGCGGAATCGCGATTCCTCACCTGGAGGGTTTAACCAATGTTTCCAACAGCTGGTATAGCACGTCTAATATATGGCCAAAATTTATACTGCAGAGCCATTTCGCCTTCAGAGAATCGTTATGGCTGTTCTTGGTGTTGAGAGTCACGTATGCCAGTAACCATCGTCGATTAGCGGGGCAGCCAGGGATGGAGTAGT'

a_count = 0
c_count = 0
g_count = 0
t_count = 0

for i in sequence:
   if i == 'A':
      a_count += 1
   elif i == 'C':
      c_count += 1
   elif i == 'G':
      g_count += 1
   elif i == 'T':
      t_count += 1

print(a_count, c_count, g_count, t_count)

#This will also work

#sequence.count('A')
#sequence.count('G')
#sequence.count('C')
#sequence.count('T')
